name       : libreoffice
version    : 5.3.2.2
release    : 38
source     :
    - http://download.documentfoundation.org/libreoffice/src/5.3.2/libreoffice-5.3.2.2.tar.xz : 8811a95eb9298cc89603bccd22bcf7196dcef8543b5e66dae5aa47263a0f9ead
    - http://download.documentfoundation.org/libreoffice/src/5.3.2/libreoffice-dictionaries-5.3.2.2.tar.xz : cd4705706534b2e3e50798608d27afb6e938f0e079fe28a27b3ddce032e95400
    - http://download.documentfoundation.org/libreoffice/src/5.3.2/libreoffice-help-5.3.2.2.tar.xz : 29b24202ee6ca0e1f6cd81a3c1ad98fa226225e7f2d6d4162936943c01656087
    - http://download.documentfoundation.org/libreoffice/src/5.3.2/libreoffice-translations-5.3.2.2.tar.xz : 2e5719f2f56e8f79e4925bf011dd4a39001880ea0285f0a9f31514d8d2fda95c
    - http://dev-www.libreoffice.org/src/commons-logging-1.2-src.tar.gz : 49665da5a60d033e6dff40fe0a7f9173e886ae859ce6096c1afe34c48b677c81
    - http://dev-www.libreoffice.org/src/beeca87be45ec87d241ddd0e1bad80c1-bsh-2.0b6-src.zip : 9e93c73e23aff644b17dfff656444474c14150e7f3b38b19635e622235e01c96
    - http://dev-www.libreoffice.org/src/48d647fbd8ef8889e5a7f422c1bfda94-clucene-core-2.3.3.4.tar.gz : ddfdc433dd8ad31b5c5819cc4404a8d2127472a3b720d3e744e8c51d79732eab
    - http://dev-www.libreoffice.org/src/4b87018f7fff1d054939d19920b751a0-collada2gltf-master-cb1d97788a.tar.bz2 : b0adb8e71aef80751b999c9c055e419a625c4a05184e407aef2aee28752ad8cb
    - http://dev-www.libreoffice.org/src/17410483b5b5f267aa18b7e00b65e6e0-hsqldb_1_8_0.zip : d30b13f4ba2e3b6a2d4f020c0dee0a9fb9fc6fbcc2d561f36b78da4bf3802370
    - http://dev-www.libreoffice.org/src/ba2930200c9f019c2d93a8c88c651a0f-flow-engine-0.9.4.zip : 233f66e8d25c5dd971716d4200203a612a407649686ef3b52075d04b4c9df0dd
    - http://dev-www.libreoffice.org/src/d8bd5eed178db6e2b18eeed243f85aa8-flute-1.1.6.zip : 1b5b24f7bc543c0362b667692f78db8bab4ed6dafc6172f104d0bd3757d8a133
    - http://dev-www.libreoffice.org/src/eeb2c7ddf0d302fba4bfc6e97eac9624-libbase-1.1.6.zip : 75c80359c9ce343c20aab8a36a45cb3b9ee7c61cf92c13ae45399d854423a9ba
    - http://dev-www.libreoffice.org/src/3bdf40c0d199af31923e900d082ca2dd-libfonts-1.1.6.zip : e0531091787c0f16c83965fdcbc49162c059d7f0c64669e7f119699321549743
    - http://dev-www.libreoffice.org/src/3404ab6b1792ae5f16bbd603bd1e1d03-libformula-1.1.7.zip : 5826d1551bf599b85742545f6e01a0079b93c1b2c8434bf409eddb3a29e4726b
    - http://dev-www.libreoffice.org/src/db60e4fde8dd6d6807523deb71ee34dc-liblayout-0.2.10.zip : e1fb87f3f7b980d33414473279615c4644027e013012d156efa538bc2b031772
    - http://dev-www.libreoffice.org/src/97b2d4dba862397f446b217e2b623e71-libloader-1.1.6.zip : 3d853b19b1d94a6efa69e7af90f7f2b09ecf302913bee3da796c15ecfebcfac8
    - http://dev-www.libreoffice.org/src/8ce2fcd72becf06c41f7201d15373ed9-librepository-1.1.6.zip : abe2c57ac12ba45d83563b02e240fa95d973376de2f720aab8fe11f2e621c095
    - http://dev-www.libreoffice.org/src/f94d9870737518e3b597f9265f4e9803-libserializer-1.1.6.zip : 05640a1f6805b2b2d7e2cb9c50db9a5cb084e3c52ab1a71ce015239b4a1d4343
    - http://dev-www.libreoffice.org/src/ace6ab49184e329db254e454a010f56d-libxml-1.1.7.zip : 7d2797fe9f79a77009721e3f14fa4a1dec17a6d706bdc93f85f1f01d124fab66
    - http://dev-www.libreoffice.org/src/39bb3fcea1514f1369fcfc87542390fd-sacjava-1.3.zip : 085f2112c51fa8c1783fac12fbd452650596415121348393bb51f0f7e85a9045
    - http://dev-www.libreoffice.org/src/language-subtag-registry-2016-07-19.tar.bz2 : e3dc30bdbfdad442c542dc0e165df9d8d2ba06a357cd55957155d8259d1661dc
    - http://dev-www.libreoffice.org/src/86b1daaa438f5a7bea9a52d7b9799ac0-xmlsec1-1.2.23.tar.gz : 41d463d16c9894cd3317098d027c038039c6d896b9cbb9bad9c4e29959e10e9f
    - http://dev-www.libreoffice.org/src/26b3e95ddf3d9c077c480ea45874b3b8-lp_solve_5.5.tar.gz : 171816288f14215c69e730f7a4f1c325739873e21f946ff83884b350574e6695
    - http://dev-www.libreoffice.org/src/368f114c078f94214a308a74c7e991bc-crosextrafonts-20130214.tar.gz : c48d1c2fd613c9c06c959c34da7b8388059e2408d2bb19845dc3ed35f76e4d09
    - http://dev-www.libreoffice.org/src/c74b7223abe75949b4af367942d96c7a-crosextrafonts-carlito-20130920.tar.gz : 4bd12b6cbc321c1cf16da76e2c585c925ce956a08067ae6f6c64eff6ccfdaf5a
    - http://dev-www.libreoffice.org/src/33e1e61fab06a547851ed308b4ffef42-dejavu-fonts-ttf-2.37.zip : 7576310b219e04159d35ff61dd4a4ec4cdba4f35c00e002a136f00e96a908b0a
    - http://dev-www.libreoffice.org/src/1725634df4bb3dcb1b2c91a6175f8789-GentiumBasic_1102.zip : 2f1a2c5491d7305dffd3520c6375d2f3e14931ee35c6d8ae1e8f098bf1a7b3cc
    - http://dev-www.libreoffice.org/src/134d8262145fc793c6af494dcace3e71-liberation-fonts-ttf-1.07.4.tar.gz : 61a7e2b6742a43c73e8762cdfeaf6dfcf9abdd2cfa0b099a9854d69bc4cfee5c
    - http://dev-www.libreoffice.org/src/5c781723a0d9ed6188960defba8e91cf-liberation-fonts-ttf-2.00.1.tar.gz : 7890278a6cd17873c57d9cd785c2d230d9abdea837e96516019c5885dd271504
    - http://dev-www.libreoffice.org/src/e7a384790b13c29113e22e596ade9687-LinLibertineG-20120116.zip : 54adcb2bc8cac0927a647fbd9362f45eff48130ce6e2379dc3867643019e08c5
    - http://dev-www.libreoffice.org/src/7a15edea7d415ac5150ea403e27401fd-open-sans-font-ttf-1.10.tar.gz : cc80fd415e57ecec067339beadd0eef9eaa45e65d3c51a922ba5f9172779bfb8
    - http://dev-www.libreoffice.org/src/c3c1a8ba7452950636e871d25020ce0d-pt-serif-font-1.0000W.tar.gz : 6757feb23f889a82df59679d02b8ee1f907df0a0ac1c49cdb48ed737b60e5dfa
    - http://dev-www.libreoffice.org/src/907d6e99f241876695c19ff3db0b8923-source-code-pro-2.030R-ro-1.050R-it.tar.gz : 09466dce87653333f189acd8358c60c6736dcd95f042dee0b644bdcf65b6ae2f
    - http://dev-www.libreoffice.org/src/edc4d741888bc0d38e32dbaa17149596-source-sans-pro-2.010R-ro-1.065R-it.tar.gz : e7bc9a1fec787a529e49f5a26b93dcdcf41506449dfc70f92cdef6d17eb6fb61
    - http://dev-www.libreoffice.org/src/OpenCOLLADA-master-6509aa13af.tar.bz2 : 8f25d429237cde289a448c82a0a830791354ccce5ee40d77535642e46367d6c4
    - http://dev-www.libreoffice.org/src/a39f6c07ddb20d7dd2ff1f95fa21e2cd-raptor2-2.0.15.tar.gz : ada7f0ba54787b33485d090d3d2680533520cd4426d2f7fb4782dd4a6a1480ed
    - http://dev-www.libreoffice.org/src/1f5def51ca0026cd192958ef07228b52-rasqal-0.9.33.tar.gz : 6924c9ac6570bd241a9669f83b467c728a322470bf34f4b2da4f69492ccfd97c
    - http://dev-www.libreoffice.org/src/e5be03eda13ef68aabab6e42aa67715e-redland-1.0.17.tar.gz : de1847f7b59021c16bdc72abb4d8e2d9187cd6124d69156f3326dd34ee043681
    - http://dev-www.libreoffice.org/src/798b2ffdc8bcfe7bca2cf92b62caf685-rhino1_5R5.zip : 1fb458d6aab06932693cc8a9b6e4e70944ee1ff052fa63606e3131df34e21753
    - http://dev-www.libreoffice.org/src/35c94d2df8893241173de1d16b6034c0-swingExSrc.zip : 64585ac36a81291a58269ec5347e7e3e2e8596dbacb9221015c208191333c6e1
    - http://dev-www.libreoffice.org/src/0168229624cfac409e766913506961a8-ucpp-1.3.2.tar.gz : 983941d31ee8d366085cadf28db75eb1f5cb03ba1e5853b98f12f7f51c63b776
    - http://dev-www.libreoffice.org/src/libgltf/libgltf-0.0.2.tar.bz2 : d1cc7297ed1921aa969e26413b4c4e18afc882ce4d2f5a2aa2a2905706f7206b
    - http://dev-www.libreoffice.org/src/EmojiOneColor-SVGinOT-1.3.tar.gz : d1a08f7c10589f22740231017694af0a7a270760c8dec33d8d1c038e2be0a0c7
    - http://dev-www.libreoffice.org/src/libstaroffice-0.0.2.tar.bz2 : f06eb29d13357f1aa1944de0be1162de05d9f9333b5f54e9bf762415029a8899
    - http://dev-www.libreoffice.org/src/libzmf-0.0.1.tar.bz2 : b69f7f6e94cf695c4b672ca65def4825490a1e7dee34c2126309b96d21a19e6b
    - http://dev-www.libreoffice.org/extern/a084cd548b586552cb7d3ee51f1af969-odfvalidator-1.1.8-incubating-SNAPSHOT-jar-with-dependencies.jar : a0bd3e0186e043223bfb231a888e2bfb06c78ee2e07c2f0eca434236d173cf34
    - http://dev-www.libreoffice.org/extern/8249374c274932a21846fa7629c2aa9b-officeotron-0.7.4-master.jar : f2443f27561af52324eee03a1892d9f569adc8db9e7bca55614898bc2a13a770
homepage   : http://www.libreoffice.org/
license    :
    - BSD
    - GPL-2.0+
    - LGPL-2.0+
    - MPL-1.1
    - CDDL
    - Netscape
    - Public-Domain
summary    : LibreOffice Office Suite
description:
    - LibreOffice Office Suite
    - all : LibreOffice Office Suite
    - calc : Calc is the spreadsheet program you've always needed.
    - draw : Draw lets you produce anything from a quick sketch to a complex plan,
        and gives you the means to communicate with graphics and diagrams.
    - impress : Impress is a truly outstanding tool for creating effective multimedia
        presentations.
    - math : Math is LibreOffice's formula editor
    - writer : Writer has all the features you need from a modern, full-featured word
        processing and desktop publishing tool.
builddeps  :
    - pkgconfig(coinmp)
    - pkgconfig(cppunit)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(glew)
    - pkgconfig(glm)
    - pkgconfig(glu)
    - pkgconfig(graphite2)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(harfbuzz)
    - pkgconfig(hunspell)
    - pkgconfig(icu-i18n)
    - pkgconfig(lcms2)
    - pkgconfig(libabw-0.1)
    - pkgconfig(libcdr-0.1)
    - pkgconfig(libcmis-0.5)
    - pkgconfig(libcurl)
    - pkgconfig(libe-book-0.1)
    - pkgconfig(libetonyek-0.1)
    - pkgconfig(libexttextcat)
    - pkgconfig(libfreehand-0.1)
    - pkgconfig(liblangtag)
    - pkgconfig(libmspub-0.1)
    - pkgconfig(libmwaw-0.3)
    - pkgconfig(libodfgen-0.1)
    - pkgconfig(liborcus-0.12)
    - pkgconfig(libpagemaker-0.0)
    - pkgconfig(libpng)
    - pkgconfig(librevenge-0.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libvisio-0.1)
    - pkgconfig(libwpd-0.10)
    - pkgconfig(libwpg-0.3)
    - pkgconfig(libwps-0.4)
    - pkgconfig(libxslt)
    - pkgconfig(mdds-1.2)
    - pkgconfig(mythes)
    - pkgconfig(neon)
    - pkgconfig(nss)
    - pkgconfig(poppler)
    - pkgconfig(python-3.5)
    - pkgconfig(sane-backends)
    - pkgconfig(bluez)
    - apache-ant
    - cups-devel
    - gperf
    - hyphen-devel
    - libboost-devel
    - libgcrypt-devel
    - libjpeg-turbo-devel
    - libxt-devel
    - openblas-devel
    - openjdk-8
    - openldap-devel
    - perl-archive-zip
    - python3
    - unixodbc-devel
rundeps    :
    - writer : libreoffice-common
    - calc : libreoffice-writer
    - impress :
        - libreoffice-draw
        - libreoffice-writer
    - math : libreoffice-writer
    - draw : libreoffice-writer
    - base : libreoffice-writer
    - writer-help : libreoffice-common-help
    - calc-help : libreoffice-common-help
    - impress-help : libreoffice-common-help
    - draw-help : libreoffice-common-help
    - base-help : libreoffice-common-help
    - all :
        - libreoffice-base
        - libreoffice-calc
        - libreoffice-common
        - libreoffice-draw
        - libreoffice-impress
        - libreoffice-math
        - libreoffice-writer
component  :
    - office
    - common : office
    - writer : office
    - writer-help : office
    - calc : office
    - calc-help : office
    - impress : office
    - impress-help : office
    - base : office
    - base-help : office
    - draw : office
    - draw-help : office
    - all : office
patterns   :
    - common : /*
    - common-help :
        - /usr/lib/libreoffice/help/*/*
        - /usr/lib/libreoffice/help/*.xsl
    - base-help :
        - /usr/lib/libreoffice/help/*/sdatabase*
    - base :
        - /usr/bin/lobase
        - /usr/lib/libreoffice/program/sbase
        - /usr/lib/libreoffice/share/registry/base.xcd
        - /usr/lib/libreoffice/share/xdg/base.desktop
        - /usr/share/applications/libreoffice-base.desktop
        - /usr/share/man/man1/lobase.1.gz
        - /usr/share/icons/*/*/apps/libreoffice-base*
        - /usr/share/appdata/libreoffice-base.appdata.xml
    - calc-help :
        - /usr/lib/libreoffice/help/*/scalc*
    - calc :
        - /usr/bin/localc
        - /usr/lib/libreoffice/program/scalc
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/scalc/*
        - /usr/lib/libreoffice/share/registry/calc.xcd
        - /usr/lib/libreoffice/share/xdg/calc.desktop
        - /usr/share/applications/libreoffice-calc.desktop
        - /usr/share/man/man1/localc.1.gz
        - /usr/share/icons/*/*/apps/libreoffice-calc*
        - /usr/share/appdata/libreoffice-calc.appdata.xml
    - common-dictionaries :
        - /usr/lib/libreoffice/share/extensions/dict-*/*
        - /usr/lib/libreoffice/share/extensions/package.txt
    - draw-help :
        - /usr/lib/libreoffice/help/*/sdraw*
    - draw :
        - /usr/bin/lodraw
        - /usr/lib/libreoffice/program/sdraw
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/sdraw/*
        - /usr/lib/libreoffice/share/registry/draw.xcd
        - /usr/lib/libreoffice/share/xdg/draw.desktop
        - /usr/share/applications/libreoffice-draw.desktop
        - /usr/share/man/man1/lodraw.1.gz
        - /usr/share/icons/*/*/apps/libreoffice-draw*
        - /usr/share/appdata/libreoffice-draw.appdata.xml
    - impress-help :
        - /usr/lib/libreoffice/help/*/simpress*
    - impress :
        - /usr/bin/loimpress
        - /usr/lib/libreoffice/program/simpress
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/simpress/*
        - /usr/lib/libreoffice/share/config/soffice.cfg/simpress/*
        - /usr/lib/libreoffice/share/registry/impress.xcd
        - /usr/lib/libreoffice/share/xdg/impress.desktop
        - /usr/share/applications/libreoffice-impress.desktop
        - /usr/share/man/man1/loimpress.1.gz
        - /usr/share/icons/*/*/apps/libreoffice-impress*
        - /usr/share/appdata/libreoffice-impress.appdata.xml
    - math-help :
        - /usr/lib/libreoffice/help/*/smath*
    - math :
        - /usr/bin/lomath
        - /usr/lib/libreoffice/program/smath
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/smath/*
        - /usr/lib/libreoffice/share/registry/math.xcd
        - /usr/lib/libreoffice/share/xdg/math.desktop
        - /usr/share/applications/libreoffice-math.desktop
        - /usr/share/man/man1/lomath.1.gz
        - /usr/share/icons/*/*/apps/libreoffice-math*
    - writer-help :
        - /usr/lib/libreoffice/help/*/swriter*
    - writer :
        - /usr/bin/loweb
        - /usr/bin/lowriter
        - /usr/lib/libreoffice/program/swriter
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/swriter/*
        - /usr/lib/libreoffice/share/registry/writer.xcd
        - /usr/lib/libreoffice/share/xdg/writer.desktop
        - /usr/share/applications/libreoffice-writer.desktop
        - /usr/share/man/man1/loweb.1.gz
        - /usr/share/man/man1/lowriter.1.gz
        - /usr/share/icons/*/*/apps/libreoffice-writer*
        - /usr/share/appdata/libreoffice-writer.appdata.xml
    - all :
        - /usr/share/doc/libreoffice-all
setup      : |
    # Fix mimetypes
    sed -i 's:application/pdf;::g' sysui/desktop/menus/draw.desktop
    sed -i 's:text/plain;::g' sysui/desktop/menus/writer.desktop
    # Let LO find downloaded sources
    install -d -m 00755 external/tarballs
    for i in `ls $sources`; do
        ln -sv $sources/${i} external/tarballs/.
    done

    chmod +x bin/unpack-sources
    %patch -p1 < $pkgfiles/0001-Use-the-Sifr-style-by-default.patch
    %patch -p1 < $pkgfiles/0002-Remove-check-if-root-due-to-issue-with-fakeroot.patch
    export CFLAGS="${CFLAGS/-g2/}"
    export CXXFLAGS="${CXXFLAGS/-g2/}"
    %configure    --prefix=/usr      \
                  --sysconfdir=/etc           \
                  --libdir=/usr/lib           \
                  --libexecdir=/usr/lib/libreoffice \
                  --with-vendor="Solus"       \
                  --with-external-dict-dir=/usr/share/hunspell \
                  --with-help                 \
                  --with-lang=ALL             \
                  --with-myspell-dicts        \
                  --with-system-dicts         \
                  --enable-release-build      \
                  --enable-python=system      \
                  --with-alloc=system         \
                  --with-system-altlinuxhyph  \
                  --with-system-bluez         \
                  --with-system-boost         \
                  --with-system-bzip2         \
                  --with-system-cairo         \
                  --with-system-coinmp        \
                  --with-system-cppunit       \
                  --with-system-curl          \
                  --with-system-expat         \
                  --with-system-glew          \
                  --with-system-glm           \
                  --with-system-graphite      \
                  --with-system-harfbuzz      \
                  --with-system-hunspell      \
                  --with-system-icu           \
                  --with-system-jpeg          \
                  --with-system-lcms2         \
                  --with-system-libabw        \
                  --with-system-libcdr        \
                  --with-system-libcmis       \
                  --with-system-libebook      \
                  --with-system-libetonyek    \
                  --with-system-libexttextcat \
                  --with-system-libfreehand   \
                  --with-system-liblangtag    \
                  --with-system-libmspub      \
                  --with-system-libmwaw       \
                  --with-system-libodfgen     \
                  --with-system-libpagemaker  \
                  --with-system-libpng        \
                  --with-system-librevenge    \
                  --with-system-libvisio      \
                  --with-system-libwpd        \
                  --with-system-libwpg        \
                  --with-system-libwps        \
                  --with-system-libxml        \
                  --with-system-mdds          \
                  --with-system-mythes        \
                  --with-system-neon          \
                  --with-system-nss           \
                  --with-system-odbc          \
                  --with-system-openldap      \
                  --with-system-openssl       \
                  --with-system-orcus         \
                  --with-system-poppler       \
                  --with-system-sane          \
                  --with-system-zlib          \
                  --without-junit             \
                  --disable-debug             \
                  --disable-firebird-sdbc     \
                  --enable-gtk3               \
                  --disable-odk               \
                  --disable-postgresql-sdbc   \
                  --disable-symbols           \
                  --with-parallelism=%YJOBS%
build      : |
    make build-nocheck
install    : |
    make install DESTDIR="$installdir" distro-pack-install
    # Sometimes we have a missing ure-link. LibreOffice kinda gets annoyed.
    ln -sf /usr/lib/libreoffice/ure %installroot%/usr/lib/libreoffice/ure-link

    # Make a meta package
    install -D -d -m 00755 $installdir/usr/share/doc
    echo "LibreOffice Meta Package" > $installdir/usr/share/doc/libreoffice-all
