name        : libreoffice
version     : 5.1.2.2
release     : 15
source      :
    - http://download.documentfoundation.org/libreoffice/src/5.1.2/libreoffice-5.1.2.2.tar.xz : 54ecdc9e0201a64fb6a0898b2e5ebd6c6e22c36965e3eb797ae351219e441781
    - http://download.documentfoundation.org/libreoffice/src/5.1.2/libreoffice-dictionaries-5.1.2.2.tar.xz : c500d21160a22808986b80230c71a1eff8b2f2102e2d5f9d1d543dcfa698a03e
    - http://download.documentfoundation.org/libreoffice/src/5.1.2/libreoffice-help-5.1.2.2.tar.xz : dc4d9fd6ca78ad89069ca1f0187f274c9cd83fb8849716193d25bce6ca072953
    - http://download.documentfoundation.org/libreoffice/src/5.1.2/libreoffice-translations-5.1.2.2.tar.xz : 7fbf0d742df7d9a5cf567bb8b8d78e16160936a6f339b9d035e0ac9e1d2455f0
homepage    : http://www.libreoffice.org/
license     :
    - BSD
    - GPL-2.0+
    - LGPL-2.0+
    - MPL-1.1
    - CDDL
    - Netscape
    - Public-Domain
summary     : LibreOffice Office Suite
component   : office
builddeps   :
    - cups-devel
    - gperf
    - libboost-devel
    - libgcrypt-devel
    - libjpeg-turbo-devel
    - libxt-devel
    - perl-archive-zip
    - pkgconfig(glu)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-i18n)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(poppler)
    - pkgconfig(python-3.5)
    - python3
description : |
    LibreOffice Office Suite
patterns   :
    - common: /*
    - common-help: /usr/lib/libreoffice/help/*/*
    - common-help: /usr/lib/libreoffice/help/*.xsl
    - base-help: /usr/lib/libreoffice/help/*/sdatabase*
    - base: /usr/bin/lobase
    - base: /usr/lib/libreoffice/program/sbase
    - base: /usr/lib/libreoffice/share/registry/base.xcd
    - base: /usr/lib/libreoffice/share/xdg/base.desktop
    - base: /usr/share/applications/libreoffice-base.desktop
    - base: /usr/share/man/man1/lobase.1.gz
    - calc-help: /usr/lib/libreoffice/help/*/scalc*
    - calc: /usr/bin/localc
    - calc: /usr/lib/libreoffice/program/scalc
    - calc: /usr/lib/libreoffice/share/config/soffice.cfg/modules/scalc/*
    - calc: /usr/lib/libreoffice/share/registry/calc.xcd
    - calc: /usr/lib/libreoffice/share/xdg/calc.desktop
    - calc: /usr/share/applications/libreoffice-calc.desktop
    - calc: /usr/share/man/man1/localc.1.gz
    - common-dictionaries: /usr/lib/libreoffice/share/extensions/dict-*/*
    - common-dictionaries: /usr/lib/libreoffice/share/extensions/package.txt
    - draw-help: /usr/lib/libreoffice/help/*/sdraw*
    - draw: /usr/bin/lodraw
    - draw: /usr/lib/libreoffice/program/sdraw
    - draw: /usr/lib/libreoffice/share/config/soffice.cfg/modules/sdraw/*
    - draw: /usr/lib/libreoffice/share/registry/draw.xcd
    - draw: /usr/lib/libreoffice/share/xdg/draw.desktop
    - draw: /usr/share/applications/libreoffice-draw.desktop
    - draw: /usr/share/man/man1/lodraw.1.gz
    - impress-help: /usr/lib/libreoffice/help/*/simpress*
    - impress: /usr/bin/loimpress
    - impress: /usr/lib/libreoffice/program/simpress
    - impress: /usr/lib/libreoffice/share/config/soffice.cfg/modules/simpress/*
    - impress: /usr/lib/libreoffice/share/config/soffice.cfg/simpress/*
    - impress: /usr/lib/libreoffice/share/registry/impress.xcd
    - impress: /usr/lib/libreoffice/share/xdg/impress.desktop
    - impress: /usr/share/applications/libreoffice-impress.desktop
    - impress: /usr/share/man/man1/loimpress.1.gz
    - math-help: /usr/lib/libreoffice/help/*/smath*
    - math: /usr/bin/lomath
    - math: /usr/lib/libreoffice/program/smath
    - math: /usr/lib/libreoffice/share/config/soffice.cfg/modules/smath/*
    - math: /usr/lib/libreoffice/share/registry/math.xcd
    - math: /usr/lib/libreoffice/share/xdg/math.desktop
    - math: /usr/share/applications/libreoffice-math.desktop
    - math: /usr/share/man/man1/lomath.1.gz
    - writer-help: /usr/lib/libreoffice/help/*/swriter*
    - writer: /usr/bin/loweb
    - writer: /usr/bin/lowriter
    - writer: /usr/lib/libreoffice/program/swriter
    - writer: /usr/lib/libreoffice/share/config/soffice.cfg/modules/swriter/*
    - writer: /usr/lib/libreoffice/share/registry/writer.xcd
    - writer: /usr/lib/libreoffice/share/xdg/writer.desktop
    - writer: /usr/share/applications/libreoffice-writer.desktop
    - writer: /usr/share/man/man1/loweb.1.gz
    - writer: /usr/share/man/man1/lowriter.1.gz
setup      : |
    tar xvf $sources/libreoffice-dictionaries-${version}.tar.xz
    tar xvf $sources/libreoffice-help-${version}.tar.xz
    tar xvf $sources/libreoffice-translations-${version}.tar.xz
    chmod +x bin/unpack-sources
    #%patch -p1 < $pkgfiles/0001-Use-the-Sifr-style-by-default.patch
    ./autogen.sh --prefix=/usr      \
                  --sysconfdir=/etc           \
                  --with-vendor="Solus Operating System" \
                  --with-lang=ALL             \
                  --with-help                 \
                  --with-myspell-dicts        \
                  --with-alloc=system         \
                  --without-java              \
                  --without-system-dicts      \
                  --disable-odk               \
                  --disable-postgresql-sdbc   \
                  --enable-release-build=yes  \
                  --enable-python=system      \
                  --without-system-boost      \
                  --with-system-cairo         \
                  --with-system-curl          \
                  --with-system-expat         \
                  --with-system-harfbuzz      \
                  --with-system-icu           \
                  --with-system-jpeg          \
                  --with-system-lcms2         \
                  --with-system-libpng        \
                  --with-system-libxml        \
                  --with-system-nss           \
                  --with-system-openssl       \
                  --with-system-poppler       \
                  --with-system-zlib          \
                  --disable-gtk3              \
                  --with-parallelism=%JOBS%
build      : |
    %make build-nocheck
install    : |
    %make_install distro-pack-install
    # Sometimes we have a missing ure-link. LibreOffice kinda gets annoyed.
    ln -sf /usr/lib/libreoffice/ure %installroot%/usr/lib/libreoffice/ure-link
