name        : libreoffice
version     : 5.1.4.2
release     : 19
source      :
    - http://download.documentfoundation.org/libreoffice/src/5.1.4/libreoffice-5.1.4.2.tar.xz : cae54a79ed858ad92044179b5c33bd29c5770a8eccde04ed80c5ebfd92078385
    - http://download.documentfoundation.org/libreoffice/src/5.1.4/libreoffice-dictionaries-5.1.4.2.tar.xz : 1e38549406858d1915cedf16a4d9795c9a8226b9baf89cc0a2b1c001c7cb3063
    - http://download.documentfoundation.org/libreoffice/src/5.1.4/libreoffice-help-5.1.4.2.tar.xz : 60356c3e3a8e5ba8216c18e127cfa2b7d0eb55c69e50f056e8f78a7d9dc735cc
    - http://download.documentfoundation.org/libreoffice/src/5.1.4/libreoffice-translations-5.1.4.2.tar.xz : 73edd75925fa14adea2e1577c7b80d5693af74c303c4d313af194e2de2746c23
homepage    : http://www.libreoffice.org/
license     :
    - BSD
    - GPL-2.0+
    - LGPL-2.0+
    - MPL-1.1
    - CDDL
    - Netscape
    - Public-Domain
summary     : LibreOffice Office Suite
builddeps   :
    - pkgconfig(glu)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-i18n)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(graphite2)
    - pkgconfig(nss)
    - pkgconfig(poppler)
    - pkgconfig(python-3.5)
    - pkgconfig(sane-backends)
    - pkgconfig(bluez)
    - cups-devel
    - gperf
    - libboost-devel
    - libgcrypt-devel
    - libjpeg-turbo-devel
    - libxt-devel
    - perl-archive-zip
    - python3
    - unixodbc-devel
description : |
    LibreOffice Office Suite
rundeps     :
    - writer: libreoffice-common
    - calc: libreoffice-writer
    - impress: libreoffice-writer
    - math: libreoffice-writer
    - draw: libreoffice-writer
    - base: libreoffice-writer
    - writer-help: libreoffice-common-help
    - calc-help: libreoffice-common-help
    - impress-help: libreoffice-common-help
    - draw-help: libreoffice-common-help
    - base-help: libreoffice-common-help
component  :
    - office
    - common: office
    - writer: office
    - writer-help: office
    - calc: office
    - calc-help: office
    - impress: office
    - impress-help: office
    - base: office
    - base-help: office
    - draw: office
    - draw-help: office
patterns   :
    - common: /*
    - common-help:
        - /usr/lib/libreoffice/help/*/*
        - /usr/lib/libreoffice/help/*.xsl
    - base-help:
        - /usr/lib/libreoffice/help/*/sdatabase*
    - base:
        - /usr/bin/lobase
        - /usr/lib/libreoffice/program/sbase
        - /usr/lib/libreoffice/share/registry/base.xcd
        - /usr/lib/libreoffice/share/xdg/base.desktop
        - /usr/share/applications/libreoffice-base.desktop
        - /usr/share/man/man1/lobase.1.gz
    - calc-help:
        - /usr/lib/libreoffice/help/*/scalc*
    - calc:
        - /usr/bin/localc
        - /usr/lib/libreoffice/program/scalc
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/scalc/*
        - /usr/lib/libreoffice/share/registry/calc.xcd
        - /usr/lib/libreoffice/share/xdg/calc.desktop
        - /usr/share/applications/libreoffice-calc.desktop
        - /usr/share/man/man1/localc.1.gz
    - common-dictionaries:
        - /usr/lib/libreoffice/share/extensions/dict-*/*
        - /usr/lib/libreoffice/share/extensions/package.txt
    - draw-help:
        - /usr/lib/libreoffice/help/*/sdraw*
    - draw:
        - /usr/bin/lodraw
        - /usr/lib/libreoffice/program/sdraw
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/sdraw/*
        - /usr/lib/libreoffice/share/registry/draw.xcd
        - /usr/lib/libreoffice/share/xdg/draw.desktop
        - /usr/share/applications/libreoffice-draw.desktop
        - /usr/share/man/man1/lodraw.1.gz
    - impress-help:
        - /usr/lib/libreoffice/help/*/simpress*
    - impress:
        - /usr/bin/loimpress
        - /usr/lib/libreoffice/program/simpress
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/simpress/*
        - /usr/lib/libreoffice/share/config/soffice.cfg/simpress/*
        - /usr/lib/libreoffice/share/registry/impress.xcd
        - /usr/lib/libreoffice/share/xdg/impress.desktop
        - /usr/share/applications/libreoffice-impress.desktop
        - /usr/share/man/man1/loimpress.1.gz
    - math-help:
        - /usr/lib/libreoffice/help/*/smath*
    - math:
        - /usr/bin/lomath
        - /usr/lib/libreoffice/program/smath
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/smath/*
        - /usr/lib/libreoffice/share/registry/math.xcd
        - /usr/lib/libreoffice/share/xdg/math.desktop
        - /usr/share/applications/libreoffice-math.desktop
        - /usr/share/man/man1/lomath.1.gz
    - writer-help:
        - /usr/lib/libreoffice/help/*/swriter*
    - writer:
        - /usr/bin/loweb
        - /usr/bin/lowriter
        - /usr/lib/libreoffice/program/swriter
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/swriter/*
        - /usr/lib/libreoffice/share/registry/writer.xcd
        - /usr/lib/libreoffice/share/xdg/writer.desktop
        - /usr/share/applications/libreoffice-writer.desktop
        - /usr/share/man/man1/loweb.1.gz
        - /usr/share/man/man1/lowriter.1.gz
setup      : |
    tar xf $sources/libreoffice-dictionaries-${version}.tar.xz
    tar xf $sources/libreoffice-help-${version}.tar.xz
    tar xf $sources/libreoffice-translations-${version}.tar.xz
    chmod +x bin/unpack-sources
    %patch -p1 < $pkgfiles/0001-Use-the-Sifr-style-by-default.patch
    export CFLAGS="${CFLAGS/-g2/}"
    export CXXFLAGS="${CXXFLAGS/-g2/}"
    %configure    --prefix=/usr      \
                  --sysconfdir=/etc           \
                  --libdir=/usr/lib           \
                  --libexecdir=/usr/lib/libreoffice \
                  --with-vendor="Solus"       \
                  --with-lang=ALL             \
                  --with-help                 \
                  --with-myspell-dicts        \
                  --with-alloc=system         \
                  --without-java              \
                  --without-system-dicts      \
                  --disable-odk               \
                  --disable-postgresql-sdbc   \
                  --enable-release-build=yes  \
                  --enable-python=system      \
                  --without-system-boost      \
                  --with-system-cairo         \
                  --with-system-curl          \
                  --with-system-expat         \
                  --with-system-harfbuzz      \
                  --with-system-icu           \
                  --with-system-jpeg          \
                  --with-system-lcms2         \
                  --with-system-libpng        \
                  --with-system-libxml        \
                  --with-system-nss           \
                  --with-system-openssl       \
                  --with-system-poppler       \
                  --with-system-zlib          \
                  --with-system-graphite      \
                  --with-system-bluez         \
                  --with-system-odbc          \
                  --with-system-sane          \
                  --with-system-bzip2         \
                  --disable-gtk3              \
                  --disable-symbols           \
                  --disable-debug             \
                  --with-parallelism=%JOBS%
build      : |
    %make build-nocheck
install    : |
    %make_install distro-pack-install
    # Sometimes we have a missing ure-link. LibreOffice kinda gets annoyed.
    ln -sf /usr/lib/libreoffice/ure %installroot%/usr/lib/libreoffice/ure-link
