name       : libreoffice
version    : 5.2.3.3
release    : 29
source     :
    - http://download.documentfoundation.org/libreoffice/src/5.2.3/libreoffice-5.2.3.3.tar.xz : a8f1365d166bf24ac4b97ed8466f46cca29cf72e7e992bb84d24c3dc8e1c32c1
    - http://download.documentfoundation.org/libreoffice/src/5.2.3/libreoffice-dictionaries-5.2.3.3.tar.xz : c40ac3a1381c3c6e8281df1b7d9eb5f99db794a32012e45762b0847b520529a5
    - http://download.documentfoundation.org/libreoffice/src/5.2.3/libreoffice-help-5.2.3.3.tar.xz : 443be26b35c6b454d5d1ca17c58cc33ae90946f8e1003a98118467b49989cd3a
    - http://download.documentfoundation.org/libreoffice/src/5.2.3/libreoffice-translations-5.2.3.3.tar.xz : 8401e51c4b91cd47f103ba09519f0b5b9213561b7d6296ff5bdc2d1622950a48
    - http://dev-www.libreoffice.org/src/commons-logging-1.2-src.tar.gz : 49665da5a60d033e6dff40fe0a7f9173e886ae859ce6096c1afe34c48b677c81
    - http://dev-www.libreoffice.org/src/beeca87be45ec87d241ddd0e1bad80c1-bsh-2.0b6-src.zip : 9e93c73e23aff644b17dfff656444474c14150e7f3b38b19635e622235e01c96
    - http://dev-www.libreoffice.org/src/48d647fbd8ef8889e5a7f422c1bfda94-clucene-core-2.3.3.4.tar.gz : ddfdc433dd8ad31b5c5819cc4404a8d2127472a3b720d3e744e8c51d79732eab
    - http://dev-www.libreoffice.org/src/4b87018f7fff1d054939d19920b751a0-collada2gltf-master-cb1d97788a.tar.bz2 : b0adb8e71aef80751b999c9c055e419a625c4a05184e407aef2aee28752ad8cb
    - http://dev-www.libreoffice.org/src/17410483b5b5f267aa18b7e00b65e6e0-hsqldb_1_8_0.zip : d30b13f4ba2e3b6a2d4f020c0dee0a9fb9fc6fbcc2d561f36b78da4bf3802370
    - http://dev-www.libreoffice.org/src/ba2930200c9f019c2d93a8c88c651a0f-flow-engine-0.9.4.zip : 233f66e8d25c5dd971716d4200203a612a407649686ef3b52075d04b4c9df0dd
    - http://dev-www.libreoffice.org/src/d8bd5eed178db6e2b18eeed243f85aa8-flute-1.1.6.zip : 1b5b24f7bc543c0362b667692f78db8bab4ed6dafc6172f104d0bd3757d8a133
    - http://dev-www.libreoffice.org/src/eeb2c7ddf0d302fba4bfc6e97eac9624-libbase-1.1.6.zip : 75c80359c9ce343c20aab8a36a45cb3b9ee7c61cf92c13ae45399d854423a9ba
    - http://dev-www.libreoffice.org/src/3bdf40c0d199af31923e900d082ca2dd-libfonts-1.1.6.zip : e0531091787c0f16c83965fdcbc49162c059d7f0c64669e7f119699321549743
    - http://dev-www.libreoffice.org/src/3404ab6b1792ae5f16bbd603bd1e1d03-libformula-1.1.7.zip : 5826d1551bf599b85742545f6e01a0079b93c1b2c8434bf409eddb3a29e4726b
    - http://dev-www.libreoffice.org/src/db60e4fde8dd6d6807523deb71ee34dc-liblayout-0.2.10.zip : e1fb87f3f7b980d33414473279615c4644027e013012d156efa538bc2b031772
    - http://dev-www.libreoffice.org/src/97b2d4dba862397f446b217e2b623e71-libloader-1.1.6.zip : 3d853b19b1d94a6efa69e7af90f7f2b09ecf302913bee3da796c15ecfebcfac8
    - http://dev-www.libreoffice.org/src/8ce2fcd72becf06c41f7201d15373ed9-librepository-1.1.6.zip : abe2c57ac12ba45d83563b02e240fa95d973376de2f720aab8fe11f2e621c095
    - http://dev-www.libreoffice.org/src/f94d9870737518e3b597f9265f4e9803-libserializer-1.1.6.zip : 05640a1f6805b2b2d7e2cb9c50db9a5cb084e3c52ab1a71ce015239b4a1d4343
    - http://dev-www.libreoffice.org/src/ace6ab49184e329db254e454a010f56d-libxml-1.1.7.zip : 7d2797fe9f79a77009721e3f14fa4a1dec17a6d706bdc93f85f1f01d124fab66
    - http://dev-www.libreoffice.org/src/39bb3fcea1514f1369fcfc87542390fd-sacjava-1.3.zip : 085f2112c51fa8c1783fac12fbd452650596415121348393bb51f0f7e85a9045
    - http://dev-www.libreoffice.org/src/language-subtag-registry-2016-07-19.tar.bz2 : e3dc30bdbfdad442c542dc0e165df9d8d2ba06a357cd55957155d8259d1661dc
    - http://dev-www.libreoffice.org/src/ce12af00283eb90d9281956524250d6e-xmlsec1-1.2.20.tar.gz : 3221593ca50f362b546a0888a1431ad24be1470f96b2469c0e0df5e1c55e7305
    - http://dev-www.libreoffice.org/src/26b3e95ddf3d9c077c480ea45874b3b8-lp_solve_5.5.tar.gz : 171816288f14215c69e730f7a4f1c325739873e21f946ff83884b350574e6695
    - http://dev-www.libreoffice.org/src/368f114c078f94214a308a74c7e991bc-crosextrafonts-20130214.tar.gz : c48d1c2fd613c9c06c959c34da7b8388059e2408d2bb19845dc3ed35f76e4d09
    - http://dev-www.libreoffice.org/src/c74b7223abe75949b4af367942d96c7a-crosextrafonts-carlito-20130920.tar.gz : 4bd12b6cbc321c1cf16da76e2c585c925ce956a08067ae6f6c64eff6ccfdaf5a
    - http://dev-www.libreoffice.org/src/d8b5214d35bcd2bfcb2cffa7795b351d-dejavu-fonts-ttf-2.35.zip : 7e0d00f20080784c3a38a845d5858c161af14f0073d9474cdbfdedae883cc747
    - http://dev-www.libreoffice.org/src/35efabc239af896dfb79be7ebdd6e6b9-gentiumbasic-fonts-1.10.zip : f1691e48d02effdee0701622297394451759f13e0e0b36e788847f4b3e2ba11b
    - http://dev-www.libreoffice.org/src/134d8262145fc793c6af494dcace3e71-liberation-fonts-ttf-1.07.4.tar.gz : 61a7e2b6742a43c73e8762cdfeaf6dfcf9abdd2cfa0b099a9854d69bc4cfee5c
    - http://dev-www.libreoffice.org/src/5c781723a0d9ed6188960defba8e91cf-liberation-fonts-ttf-2.00.1.tar.gz : 7890278a6cd17873c57d9cd785c2d230d9abdea837e96516019c5885dd271504
    - http://dev-www.libreoffice.org/src/e7a384790b13c29113e22e596ade9687-LinLibertineG-20120116.zip : 54adcb2bc8cac0927a647fbd9362f45eff48130ce6e2379dc3867643019e08c5
    - http://dev-www.libreoffice.org/src/7a15edea7d415ac5150ea403e27401fd-open-sans-font-ttf-1.10.tar.gz : cc80fd415e57ecec067339beadd0eef9eaa45e65d3c51a922ba5f9172779bfb8
    - http://dev-www.libreoffice.org/src/c3c1a8ba7452950636e871d25020ce0d-pt-serif-font-1.0000W.tar.gz : 6757feb23f889a82df59679d02b8ee1f907df0a0ac1c49cdb48ed737b60e5dfa
    - http://dev-www.libreoffice.org/src/907d6e99f241876695c19ff3db0b8923-source-code-pro-2.030R-ro-1.050R-it.tar.gz : 09466dce87653333f189acd8358c60c6736dcd95f042dee0b644bdcf65b6ae2f
    - http://dev-www.libreoffice.org/src/edc4d741888bc0d38e32dbaa17149596-source-sans-pro-2.010R-ro-1.065R-it.tar.gz : e7bc9a1fec787a529e49f5a26b93dcdcf41506449dfc70f92cdef6d17eb6fb61
    - http://dev-www.libreoffice.org/src/OpenCOLLADA-master-6509aa13af.tar.bz2 : 8f25d429237cde289a448c82a0a830791354ccce5ee40d77535642e46367d6c4
    - http://dev-www.libreoffice.org/src/4ceb9316488b0ea01acf011023cf7fff-raptor2-2.0.9.tar.gz : e26fb9c18e6ebf71100f434070d50196a21d592b715e361850c3b4e789b5f6ef
    - http://dev-www.libreoffice.org/src/b12c5f9cfdb6b04efce5a4a186b8416b-rasqal-0.9.30.tar.gz : abf0e93d80cc79bdf383fd3e904255bf98bc729356d6cf2f673bce74b08b1cfd
    - http://dev-www.libreoffice.org/src/32f8e1417a64d3c6f2c727f9053f55ea-redland-1.0.16.tar.gz : d9a274fc086e61119d5c9beafb8d05527e040ec86f4c0961276ca8de0a049dbd
    - http://dev-www.libreoffice.org/src/798b2ffdc8bcfe7bca2cf92b62caf685-rhino1_5R5.zip : 1fb458d6aab06932693cc8a9b6e4e70944ee1ff052fa63606e3131df34e21753
    - http://dev-www.libreoffice.org/src/35c94d2df8893241173de1d16b6034c0-swingExSrc.zip : 64585ac36a81291a58269ec5347e7e3e2e8596dbacb9221015c208191333c6e1
    - http://dev-www.libreoffice.org/src/0168229624cfac409e766913506961a8-ucpp-1.3.2.tar.gz : 983941d31ee8d366085cadf28db75eb1f5cb03ba1e5853b98f12f7f51c63b776
    - http://dev-www.libreoffice.org/src/libgltf/libgltf-0.0.2.tar.bz2 : d1cc7297ed1921aa969e26413b4c4e18afc882ce4d2f5a2aa2a2905706f7206b
homepage   : http://www.libreoffice.org/
license    :
    - BSD
    - GPL-2.0+
    - LGPL-2.0+
    - MPL-1.1
    - CDDL
    - Netscape
    - Public-Domain
summary    : LibreOffice Office Suite
description:
    - LibreOffice Office Suite
    - all : LibreOffice Office Suite
    - calc : Calc is the spreadsheet program you've always needed.
    - draw : Draw lets you produce anything from a quick sketch to a complex plan,
        and gives you the means to communicate with graphics and diagrams.
    - impress : Impress is a truly outstanding tool for creating effective multimedia
        presentations.
    - math : Math is LibreOffice's formula editor
    - writer : Writer has all the features you need from a modern, full-featured word
        processing and desktop publishing tool.
builddeps  :
    - pkgconfig(coinmp)
    - pkgconfig(cppunit)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(glew)
    - pkgconfig(glm)
    - pkgconfig(glu)
    - pkgconfig(graphite2)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(harfbuzz)
    - pkgconfig(hunspell)
    - pkgconfig(icu-i18n)
    - pkgconfig(lcms2)
    - pkgconfig(libabw-0.1)
    - pkgconfig(libcdr-0.1)
    - pkgconfig(libcmis-0.5)
    - pkgconfig(libcurl)
    - pkgconfig(libe-book-0.1)
    - pkgconfig(libetonyek-0.1)
    - pkgconfig(libexttextcat)
    - pkgconfig(libfreehand-0.1)
    - pkgconfig(liblangtag)
    - pkgconfig(libmspub-0.1)
    - pkgconfig(libmwaw-0.3)
    - pkgconfig(libodfgen-0.1)
    - pkgconfig(liborcus-0.11)
    - pkgconfig(libpagemaker-0.0)
    - pkgconfig(libpng)
    - pkgconfig(librevenge-0.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libvisio-0.1)
    - pkgconfig(libwpd-0.10)
    - pkgconfig(libwpg-0.3)
    - pkgconfig(libwps-0.4)
    - pkgconfig(libxslt)
    - pkgconfig(mdds-1.2)
    - pkgconfig(mythes)
    - pkgconfig(neon)
    - pkgconfig(nss)
    - pkgconfig(poppler)
    - pkgconfig(python-3.5)
    - pkgconfig(sane-backends)
    - pkgconfig(bluez)
    - apache-ant
    - cups-devel
    - gperf
    - hyphen-devel
    - libboost-devel
    - libgcrypt-devel
    - libjpeg-turbo-devel
    - libxt-devel
    - openblas-devel
    - openjdk-8
    - openldap-devel
    - perl-archive-zip
    - python3
    - unixodbc-devel
rundeps    :
    - writer : libreoffice-common
    - calc : libreoffice-writer
    - impress :
        - libreoffice-draw
        - libreoffice-writer
    - math : libreoffice-writer
    - draw : libreoffice-writer
    - base : libreoffice-writer
    - writer-help : libreoffice-common-help
    - calc-help : libreoffice-common-help
    - impress-help : libreoffice-common-help
    - draw-help : libreoffice-common-help
    - base-help : libreoffice-common-help
    - all :
        - libreoffice-base
        - libreoffice-calc
        - libreoffice-common
        - libreoffice-draw
        - libreoffice-impress
        - libreoffice-math
        - libreoffice-writer
component  :
    - office
    - common : office
    - writer : office
    - writer-help : office
    - calc : office
    - calc-help : office
    - impress : office
    - impress-help : office
    - base : office
    - base-help : office
    - draw : office
    - draw-help : office
    - all : office
patterns   :
    - common : /*
    - common-help :
        - /usr/lib/libreoffice/help/*/*
        - /usr/lib/libreoffice/help/*.xsl
    - base-help :
        - /usr/lib/libreoffice/help/*/sdatabase*
    - base :
        - /usr/bin/lobase
        - /usr/lib/libreoffice/program/sbase
        - /usr/lib/libreoffice/share/registry/base.xcd
        - /usr/lib/libreoffice/share/xdg/base.desktop
        - /usr/share/applications/libreoffice-base.desktop
        - /usr/share/man/man1/lobase.1.gz
    - calc-help :
        - /usr/lib/libreoffice/help/*/scalc*
    - calc :
        - /usr/bin/localc
        - /usr/lib/libreoffice/program/scalc
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/scalc/*
        - /usr/lib/libreoffice/share/registry/calc.xcd
        - /usr/lib/libreoffice/share/xdg/calc.desktop
        - /usr/share/applications/libreoffice-calc.desktop
        - /usr/share/man/man1/localc.1.gz
    - common-dictionaries :
        - /usr/lib/libreoffice/share/extensions/dict-*/*
        - /usr/lib/libreoffice/share/extensions/package.txt
    - draw-help :
        - /usr/lib/libreoffice/help/*/sdraw*
    - draw :
        - /usr/bin/lodraw
        - /usr/lib/libreoffice/program/sdraw
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/sdraw/*
        - /usr/lib/libreoffice/share/registry/draw.xcd
        - /usr/lib/libreoffice/share/xdg/draw.desktop
        - /usr/share/applications/libreoffice-draw.desktop
        - /usr/share/man/man1/lodraw.1.gz
    - impress-help :
        - /usr/lib/libreoffice/help/*/simpress*
    - impress :
        - /usr/bin/loimpress
        - /usr/lib/libreoffice/program/simpress
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/simpress/*
        - /usr/lib/libreoffice/share/config/soffice.cfg/simpress/*
        - /usr/lib/libreoffice/share/registry/impress.xcd
        - /usr/lib/libreoffice/share/xdg/impress.desktop
        - /usr/share/applications/libreoffice-impress.desktop
        - /usr/share/man/man1/loimpress.1.gz
    - math-help :
        - /usr/lib/libreoffice/help/*/smath*
    - math :
        - /usr/bin/lomath
        - /usr/lib/libreoffice/program/smath
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/smath/*
        - /usr/lib/libreoffice/share/registry/math.xcd
        - /usr/lib/libreoffice/share/xdg/math.desktop
        - /usr/share/applications/libreoffice-math.desktop
        - /usr/share/man/man1/lomath.1.gz
    - writer-help :
        - /usr/lib/libreoffice/help/*/swriter*
    - writer :
        - /usr/bin/loweb
        - /usr/bin/lowriter
        - /usr/lib/libreoffice/program/swriter
        - /usr/lib/libreoffice/share/config/soffice.cfg/modules/swriter/*
        - /usr/lib/libreoffice/share/registry/writer.xcd
        - /usr/lib/libreoffice/share/xdg/writer.desktop
        - /usr/share/applications/libreoffice-writer.desktop
        - /usr/share/man/man1/loweb.1.gz
        - /usr/share/man/man1/lowriter.1.gz
    - all :
        - /usr/share/doc/libreoffice-all
setup      : |
    # Fix mimetypes
    sed -i 's:application/pdf;::g' sysui/desktop/menus/draw.desktop
    sed -i 's:text/plain;::g' sysui/desktop/menus/writer.desktop
    # Let LO find downloaded sources
    install -d -m 00755 external/tarballs
    for i in `ls $sources`; do
        ln -sv $sources/${i} external/tarballs/.
    done

    chmod +x bin/unpack-sources
    %patch -p1 < $pkgfiles/0001-Use-the-Sifr-style-by-default.patch
    export CFLAGS="${CFLAGS/-g2/}"
    export CXXFLAGS="${CXXFLAGS/-g2/}"
    %configure    --prefix=/usr      \
                  --sysconfdir=/etc           \
                  --libdir=/usr/lib           \
                  --libexecdir=/usr/lib/libreoffice \
                  --with-vendor="Solus"       \
                  --with-external-dict-dir=/usr/share/hunspell \
                  --with-help                 \
                  --with-lang=ALL             \
                  --with-myspell-dicts        \
                  --with-system-dicts         \
                  --enable-release-build      \
                  --enable-python=system      \
                  --with-system-altlinuxhyph  \
                  --with-system-bluez         \
                  --with-system-boost         \
                  --with-system-bzip2         \
                  --with-system-cairo         \
                  --with-system-coinmp        \
                  --with-system-cppunit       \
                  --with-system-curl          \
                  --with-system-expat         \
                  --with-system-glew          \
                  --with-system-glm           \
                  --with-system-graphite      \
                  --with-system-harfbuzz      \
                  --with-system-hunspell      \
                  --with-system-icu           \
                  --with-system-jpeg          \
                  --with-system-lcms2         \
                  --with-system-libabw        \
                  --with-system-libcdr        \
                  --with-system-libcmis       \
                  --with-system-libebook      \
                  --with-system-libetonyek    \
                  --with-system-libexttextcat \
                  --with-system-libfreehand   \
                  --with-system-liblangtag    \
                  --with-system-libmspub      \
                  --with-system-libmwaw       \
                  --with-system-libodfgen     \
                  --with-system-libpagemaker  \
                  --with-system-libpng        \
                  --with-system-librevenge    \
                  --with-system-libvisio      \
                  --with-system-libwpd        \
                  --with-system-libwpg        \
                  --with-system-libwps        \
                  --with-system-libxml        \
                  --with-system-mdds          \
                  --with-system-mythes        \
                  --with-system-neon          \
                  --with-system-nss           \
                  --with-system-odbc          \
                  --with-system-openldap      \
                  --with-system-openssl       \
                  --with-system-orcus         \
                  --with-system-poppler       \
                  --with-system-sane          \
                  --with-system-zlib          \
                  --without-junit             \
                  --disable-debug             \
                  --disable-firebird-sdbc     \
                  --disable-gtk3              \
                  --disable-odk               \
                  --disable-postgresql-sdbc   \
                  --disable-symbols           \
                  --with-parallelism=%YJOBS%
build      : |
    make build-nocheck
install    : |
    make install DESTDIR="$installdir" distro-pack-install
    # Sometimes we have a missing ure-link. LibreOffice kinda gets annoyed.
    ln -sf /usr/lib/libreoffice/ure %installroot%/usr/lib/libreoffice/ure-link

    # Make a meta package
    install -D -d -m 00755 $installdir/usr/share/doc
    echo "LibreOffice Meta Package" > $installdir/usr/share/doc/libreoffice-all
